# Generated by Django 5.1.4 on 2025-10-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticsconfig',
            old_name='context',
            new_name='context_type',
        ),
    ]
